use_frameworks!
swift_version = 5.0
platform :ios, '11.0'

target 'RxTestPlus_Example' do
  pod 'RxTestPlus', :path => '../'

  target 'RxTestPlus_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
